### PR TITLE
Adding documentation for C++ function searchSubstrings - Kamil

### PR DESCRIPTION
**Pull request by dusek2**
# Description
Resolved issue #28 
Function searchSubstrings needed better documentation.

ChatGPT has some captcha issues today.
I consulted Google Gemini instead.
https://g.co/gemini/share/5bb3a656355e

## Issue 
- Function to be documented
```
void searchSubstrings(std::unordered_map<std::string, int> &substringCounts, std::unordered_map<std::string, int> wordList,
                      std::string &targetString, int index, int wordLength, std::string currentSubstring)
```
- Documentation added
```
/**
* @brief Recursively searches for substrings composed of words from a word list.
*
* Recursively searches for substrings within a target string that are composed of
* words from a given word list. Counts the occurrences of each found substring.
*
* @param substringCounts An unordered_map (passed by reference) to store the counts of
*        found substrings. Keys are the substrings, values are their counts.
* @param wordList An unordered_map containing the words to search for. It is copied
*        to prevent modification of the original list.
* @param targetString The string to search within.
* @param index The starting index for the current search iteration.
* @param wordLength The length of the words in the word list.
* @param currentSubstring The substring accumulated so far in the recursive process.
*
* @note This function modifies the `substringCounts` map to store substring counts.
* @note Assumes all words in the `wordList` have the same length (`wordLength`).
* @note Assumes the `targetString` contains sufficient characters for potential substrings.
*/
```

### CODE REVIEW

**Comment by dusek2** [comment]
Image 2-26-24 at 6 31 AM

Chat GPT wants 20 20-step puzzles from me for every prompt. Had to switch to Google Gemini

**Review by Alexmc567 — APPROVED** [review]

**Review by Ruben14789 — APPROVED** [review]
approve the addition of documentation

**Review by FernFinder — APPROVED** [review]
LGTM 👍

**Comment by dusek2** [comment]
As mentioned above:

ChatGPT has some captcha issues today.
I consulted Google Gemini instead.
https://g.co/gemini/share/5bb3a656355e

**Pull request merged**
