### PR TITLE
Refactoring C++ code - Kamil

### PR DESCRIPTION
**Pull request by dusek2**
# Description
This PR resolves issue #24 "Issues with C++ code"

## Issues Addressed
**- Function displaySubstrings does not require recursion.**
```
void displaySubstrings(std::unordered_map<std::string, int>::iterator iter, std::unordered_map<std::string, int>& substringCounts)
{
    if (iter == substringCounts.end())
        return;
    std::unordered_map<std::string, int>::iterator nextIter = iter;
    nextIter++;
    displaySubstrings(nextIter, substringCounts);
    std::cout << iter->first << "\n";
    return;
}
```
Recursive function rewritten into simple loop to improve redability.
```
void displaySubstrings(const std::unordered_map<std::string, int> &substringCounts)
{
    for (const auto &pair : substringCounts)
        std::cout << pair.first << " - Count: " << pair.second << '\n';
}
```
**- The code isn't consistently styled.**

```
auto foundPosition = targetWord.find(mapIter->first);
if (foundPosition != std::string::npos)
{
    searchSubstrings(substringCountMap, wordFrequencyMap, targetWord, foundPosition, firstWordLength, mapIter->first);
}
```
Comments added throughout code and code format edited for consistent style.
```
// Find the position of the word in the target string
auto foundPosition = targetString.find(mapIter->first);
if (foundPosition != std::string::npos)
    searchSubstrings(substringCountMap, wordFrequencyMap, targetString, foundPosition, wordLength, mapIter->first);
```

**- Names could be made more meaningful.**

```
while(targetWord.size() >= firstWordLength)
```
Variable and function names edited to improve readability and portability.
```
while (targetString.size() >= wordLength)
```

**Functionality of code remained the same after refactoring.**

### CODE REVIEW

**Comment by dusek2** [comment]
ChatGPT accessed to assist with this fix for issue #24.
https://chat.openai.com/share/51a82254-ab00-4384-9acc-795e2c061275

**Comment by dusek2** [comment]
### ChatGPT provided assistance with these issues:
- Elimination of Recursive Display Function

- Consistent Coding Style

- Meaningful Names

**Review by DillonDavidson — APPROVED** [review]

**Comment by thegreatzoidberg** [comment]
Looks like it fixed all four of the issues.

**Comment by thegreatzoidberg** [comment]
Looks like it fixed all four of the issues.

**Review by thegreatzoidberg — APPROVED** [review]

**Pull request merged**
